### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by ARR4NN** [Ghosterzz/discord-ghost-transcript#1]
I need your help...
i am using Discord.js V13 and it does not work...
i get the error 
```    
 let msgs = messageCollection.array().reverse();
                                   ^

TypeError: messageCollection.array is not a function```

**Comment by Ghosterzz** [comment]
Yes hello we do not support discord v13 yet we are still working on it. We
will make a seperate package for v13 it will be out in the next two weeks

if you need t know when the v13 package is out please join our server https://discord.gg/prGGJn83sd
